#!/usr/bin/env bash
# setup_vermin.sh
# One-shot pre-Unity setup for the Vermin Exterminator repo.
# Run this ONCE after cloning, before opening Unity.
#
# Usage:
#   cd ~/Vermin-Exterminator
#   chmod +x setup_vermin.sh
#   ./setup_vermin.sh [--urp-source /path/to/temp/urp/project]
#
# What it does:
#   1. Verifies we're at the repo root.
#   2. Copies URP scaffolding (Assets/, Packages/, ProjectSettings/) from
#      either a --urp-source temp project OR creates a minimal Packages/
#      manifest so Unity will install URP on first open.
#   3. Creates Assets/Scripts/<area>/ folders and moves every .cs file to
#      the correct subfolder based on namespace.
#   4. Moves docs into Docs/.
#   5. Updates .gitignore with Unity-specific entries.
#   6. Removes repo-root clutter that Unity doesn't need.
#   7. Creates Assets/Editor/VerminProjectSetup.cs placeholder if missing.

set -euo pipefail

REPO_ROOT="$(pwd)"
URP_SOURCE=""

# -------- arg parsing --------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --urp-source)
      URP_SOURCE="$2"
      shift 2
      ;;
    -h|--help)
      sed -n '2,18p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown arg: $1" >&2
      exit 1
      ;;
  esac
done

# -------- sanity --------
if [[ ! -d ".git" ]]; then
  echo "[x] Not at a git repo root. cd into ~/Vermin-Exterminator first." >&2
  exit 1
fi

# Must be the right repo
if ! grep -q "Vermin-Exterminator\|Vermin Infestation" README.md 2>/dev/null; then
  echo "[!] README.md doesn't look like Vermin-Exterminator. Proceeding anyway in 3s..."
  sleep 3
fi

echo "== Vermin Exterminator setup starting at $REPO_ROOT =="

# -------- Step 1: URP scaffolding --------
if [[ -d "Assets" && -d "Packages" && -d "ProjectSettings" ]]; then
  echo "[=] Unity scaffolding already present — skipping."
else
  if [[ -n "$URP_SOURCE" ]]; then
    if [[ ! -d "$URP_SOURCE/Assets" || ! -d "$URP_SOURCE/Packages" || ! -d "$URP_SOURCE/ProjectSettings" ]]; then
      echo "[x] --urp-source does not look like a Unity project: $URP_SOURCE" >&2
      exit 1
    fi
    echo "[+] Copying URP scaffolding from $URP_SOURCE"
    cp -r "$URP_SOURCE/Assets" .
    cp -r "$URP_SOURCE/Packages" .
    cp -r "$URP_SOURCE/ProjectSettings" .
  else
    echo "[+] Creating minimal Unity scaffolding (Unity will install URP on first open)"
    mkdir -p Assets Packages ProjectSettings

    # Minimal manifest that asks Unity to install URP + TextMeshPro + Input System
    cat > Packages/manifest.json <<'JSON'
{
  "dependencies": {
    "com.unity.render-pipelines.universal": "16.0.6",
    "com.unity.textmeshpro": "3.2.0-pre.10",
    "com.unity.inputsystem": "1.11.2",
    "com.unity.ugui": "2.0.0",
    "com.unity.ide.visualstudio": "2.0.22",
    "com.unity.test-framework": "1.4.5",
    "com.unity.timeline": "1.8.7",
    "com.unity.visualscripting": "1.9.4",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
}
JSON

    # Minimal ProjectVersion so Hub knows which editor to use (edit if needed)
    cat > ProjectSettings/ProjectVersion.txt <<'TXT'
m_EditorVersion: 2023.2.20f1
m_EditorVersionWithRevision: 2023.2.20f1 (0e25a174756c)
TXT

    echo "[!] Minimal scaffolding created. STRONGLY RECOMMENDED: run setup with --urp-source"
    echo "    pointing at a clean URP project generated by Unity Hub for full ProjectSettings."
  fi
fi

# -------- Step 2: create Scripts/<area> folders --------
echo "[+] Creating Assets/Scripts/<area>/ folders"
mkdir -p Assets/Scripts/{AI,Camera,Data,Game,Input,Level,Pooling,Scoring,UI,Weapon}
mkdir -p Assets/Editor
mkdir -p Assets/Scenes
mkdir -p Assets/Data/Contracts
mkdir -p Assets/Settings/Volumes
mkdir -p Assets/Prefabs/UI

# -------- Step 3: move .cs files to correct folders --------
move_if_exists() {
  local dest="$1"; shift
  for f in "$@"; do
    if [[ -f "$f" ]]; then
      mv "$f" "$dest/"
      echo "    $f -> $dest/"
    fi
  done
}

echo "[+] Moving .cs files into Assets/Scripts/<area>/"

move_if_exists Assets/Scripts/AI       RatFSM.cs RatAIManager.cs MovementPathfinder.cs ScatterBehavior.cs SpawnZone.cs SpawnZoneManager.cs RatEyeShine.cs
move_if_exists Assets/Scripts/Camera   SniperCameraController.cs ZoomController.cs BreathingSway.cs
move_if_exists Assets/Scripts/Data     PlayerProgress.cs PlayerProgressManager.cs PlayerProgressUpgrades.cs SettingsData.cs SettingsManager.cs RuntimeSettings.cs RuntimeLoadout.cs ContractDefinition.cs ContractChallenge.cs ContractSet.cs
move_if_exists Assets/Scripts/Game     GameManager.cs ContractManager.cs
move_if_exists Assets/Scripts/Input    GyroInputHandler.cs TouchInputHandler.cs HybridInputController.cs InputSmoothingPipeline.cs
move_if_exists Assets/Scripts/Level    LevelGenerator.cs LevelSeedGenerator.cs EnvironmentTileDescriptor.cs EnvironmentTileLibrary.cs LightingModeController.cs
move_if_exists Assets/Scripts/Pooling  RatObjectPool.cs EffectsObjectPool.cs
move_if_exists Assets/Scripts/Scoring  ScoreManager.cs ComboTracker.cs CurrencyManager.cs
move_if_exists Assets/Scripts/UI       MainMenuController.cs HUDController.cs ScopeOverlayController.cs UpgradeShopController.cs ShopItemButton.cs HitMarkerFeedback.cs
move_if_exists Assets/Scripts/Weapon   WeaponController.cs WeaponPartCatalog.cs OpticsTierConfig.cs RecoilSystem.cs ScopeVolumeProfileSet.cs

# Any stragglers?
LEFTOVER=$(ls *.cs 2>/dev/null | wc -l)
if [[ "$LEFTOVER" != "0" ]]; then
  echo "[!] Found $LEFTOVER .cs files still at repo root. Moving to Assets/Scripts/_Unsorted/"
  mkdir -p Assets/Scripts/_Unsorted
  mv *.cs Assets/Scripts/_Unsorted/ 2>/dev/null || true
fi

# -------- Step 4: organize docs --------
echo "[+] Moving docs to Docs/"
mkdir -p Docs Docs/screenshots
for f in PHASE2-NOTES.md URP_SETUP_NOTES.md SceneSetupInstructions.md InspectorContractChecklist.md; do
  [[ -f "$f" ]] && mv "$f" Docs/ && echo "    $f -> Docs/"
done
# screenshots at root
shopt -s nullglob
for f in 2026-*.png; do mv "$f" Docs/screenshots/ 2>/dev/null || true; done
for f in 03-*.png; do mv "$f" Docs/screenshots/ 2>/dev/null || true; done
[[ -d "video_thumbs" ]] && mv video_thumbs Docs/ 2>/dev/null || true
shopt -u nullglob

# -------- Step 5: cruft cleanup --------
echo "[+] Removing root-level cruft Unity does not need"
rm -f "SYSTEM ROLE EXECUTION.txt" "SYSTEMROLEEXECUTION.txt" "SHN.json" "manager.txt" "VERMIN-HUNTER"

# -------- Step 6: .gitignore --------
echo "[+] Ensuring .gitignore covers Unity artifacts"
touch .gitignore
add_ignore() {
  local pat="$1"
  grep -qxF "$pat" .gitignore || echo "$pat" >> .gitignore
}
add_ignore ""
add_ignore "# Unity generated"
add_ignore "[Ll]ibrary/"
add_ignore "[Tt]emp/"
add_ignore "[Oo]bj/"
add_ignore "[Bb]uild/"
add_ignore "[Bb]uilds/"
add_ignore "[Ll]ogs/"
add_ignore "[Uu]ser[Ss]ettings/"
add_ignore "*.csproj"
add_ignore "*.sln"
add_ignore "*.user"
add_ignore "*.suo"
add_ignore "*.pidb"
add_ignore "*.unityproj"
add_ignore "*.apk"
add_ignore "*.aab"
add_ignore ".vs/"
add_ignore ".vscode/"
add_ignore ".idea/"

# -------- Step 7: done --------
echo ""
echo "== Setup complete =="
echo ""
echo "Next steps:"
echo "  1. Edit open_vermin.sh and set UNITY_EXE to your editor path (auto-detect will try)."
echo "  2. ./open_vermin.sh         # opens Unity at this exact project"
echo "  3. In Unity, run menu:      Vermin -> Setup All"
echo "  4. Wait ~30s, then press Play to smoke-test the MainMenu."
echo ""
echo "Summary:"
echo "  Scripts in Assets/Scripts/: $(find Assets/Scripts -name '*.cs' | wc -l) files"
echo "  Editor script path:         Assets/Editor/VerminProjectSetup.cs"
echo "  Scenes folder:              Assets/Scenes/ (empty; created by Vermin -> Setup All)"
echo "  Data folder:                Assets/Data/ (populated by Vermin -> Setup All)"
echo ""
